import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

/**
 * Build the browser overlay+chrome bundle and embed it (D-034). Produces both
 * `dist/client.js` (for inspection / dev) and `src/server/client-bundle.generated.ts`
 * (a string constant the server serves and `bun build --compile` embeds in the
 * single binary).
 */
const root = resolve(import.meta.dir, "..");

const result = await Bun.build({
  entrypoints: [resolve(root, "client/index.ts")],
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "none",
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("client build failed");
}

const output = result.outputs[0];
if (!output) throw new Error("client build produced no output");
const code = await output.text();
const hash = createHash("sha256").update(code).digest("hex").slice(0, 16);

await mkdir(resolve(root, "dist"), { recursive: true });
await writeFile(resolve(root, "dist/client.js"), code);

const generated = `// AUTO-GENERATED by scripts/build-client.ts. Do not edit by hand.
// Holds the pre-built browser overlay+chrome bundle as a string so it can be
// embedded in the \`bun build --compile\` single binary (D-034).
export const CLIENT_BUNDLE = ${JSON.stringify(code)};
export const CLIENT_BUNDLE_HASH = ${JSON.stringify(hash)};
`;
const generatedPath = resolve(root, "src/server/client-bundle.generated.ts");
await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, generated);

console.log(`client bundle: ${(code.length / 1024).toFixed(1)} KiB (sha256:${hash})`);
