import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

/**
 * Build the browser bundles and embed them (D-034). Everything the viewer needs
 * is compiled into `src/server/client-bundle.generated.ts` as strings, so
 * `bun build --compile` carries it inside the single binary: no CDN, no assets
 * on disk, and the viewer works with no network.
 *
 * Three artifacts, because the two contexts are not alike:
 * - `overlay` runs inside the artifact's sandboxed iframe. Lit + shadow DOM,
 *   kept small; it must not drag React into a document Lucid does not own.
 * - `chrome` is Lucid's own page: React + assistant-ui.
 * - `chromeCss` is Tailwind's output for the chrome. Tailwind is a separate
 *   toolchain from Bun's JS bundler, so it runs as its own step here rather
 *   than being imported from the TSX.
 *
 * The favicon rides along for the same reason: `assets/lucid-mark.svg` is the
 * mark, and the server must serve it from inside a binary that has no asset
 * directory. Embedding it here keeps one drawing of the logomark instead of a
 * hand-copied second one in the server.
 */
const root = resolve(import.meta.dir, "..");

const bundle = async (entry: string, label: string): Promise<string> => {
  const result = await Bun.build({
    entrypoints: [resolve(root, entry)],
    target: "browser",
    format: "esm",
    minify: true,
    sourcemap: "none",
    define: { "process.env.NODE_ENV": JSON.stringify("production") },
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error(`${label} build failed`);
  }
  const output = result.outputs[0];
  if (!output) throw new Error(`${label} build produced no output`);
  return output.text();
};

const buildCss = async (): Promise<string> => {
  const out = resolve(root, "dist/chrome.css");
  const proc = Bun.spawn(
    [
      "bunx",
      "@tailwindcss/cli",
      "--input",
      resolve(root, "client/chrome/styles.css"),
      "--output",
      out,
      "--minify",
    ],
    { cwd: root, stdout: "pipe", stderr: "pipe" },
  );
  const code = await proc.exited;
  if (code !== 0) {
    console.error(await new Response(proc.stderr).text());
    throw new Error("tailwind build failed");
  }
  return Bun.file(out).text();
};

const sha = (s: string): string => createHash("sha256").update(s).digest("hex").slice(0, 16);

await mkdir(resolve(root, "dist"), { recursive: true });

const [overlay, chrome, chromeCss, favicon] = await Promise.all([
  bundle("client/entry.overlay.ts", "overlay"),
  bundle("client/entry.chrome.tsx", "chrome"),
  buildCss(),
  Bun.file(resolve(root, "assets/lucid-mark.svg")).text(),
]);

await writeFile(resolve(root, "dist/client.js"), overlay);
await writeFile(resolve(root, "dist/chrome.js"), chrome);

const hash = sha(overlay + chrome + chromeCss);
const generated = `// AUTO-GENERATED by scripts/build-client.ts. Do not edit by hand.
// The pre-built browser bundles as strings, so \`bun build --compile\` embeds
// them in the single binary (D-034).
//
// CLIENT_BUNDLE is the overlay, injected into the artifact's sandboxed iframe.
// CHROME_BUNDLE + CHROME_CSS are Lucid's own viewer page.
// FAVICON_SVG is assets/lucid-mark.svg, the one drawing of the logomark.
export const CLIENT_BUNDLE = ${JSON.stringify(overlay)};
export const CHROME_BUNDLE = ${JSON.stringify(chrome)};
export const CHROME_CSS = ${JSON.stringify(chromeCss)};
export const FAVICON_SVG = ${JSON.stringify(favicon)};
export const CLIENT_BUNDLE_HASH = ${JSON.stringify(hash)};
`;
const generatedPath = resolve(root, "src/server/client-bundle.generated.ts");
await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, generated);

const kib = (s: string): string => `${(s.length / 1024).toFixed(1)} KiB`;
console.log(
  `overlay ${kib(overlay)} · chrome ${kib(chrome)} · css ${kib(chromeCss)} (sha256:${hash})`,
);
